# Workflow name
name: Deploy to GitHub Pages

# Events that trigger this workflow
on:
  push:
    branches:
      - main

jobs:
  flutter_deploy:
    name: Test, build and deploy flutter web
    # VM type and version that runs this code
    runs-on: ubuntu-latest
    steps:
      # Any prerequisite steps
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      # Module that allows us to run flutter commands
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
          flutter-version: "2.10.2"
      - run: flutter pub get
      - run: flutter analyze
#      - run: flutter test
      - run: flutter clean
      - run: flutter build web --release

      # Deploy to local repo
      - name: Push web build to gh-pages
        uses: s0/git-publish-subdir-action@v2.5.1
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: build/web
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# For developing releases using binary files (no directory based apps)

#      # Create a release
#      - name: Create a web release
#        uses: ncipollo/release-action@v1
#        with:
#          artifacts: "build/web/*"
#          tag: v1.0.${{ github.run_number }}
#          token: ${{ secrets.GITHUB_TOKEN }}


# For wider build and deployment options, run VM per build item

#  flutter_test:
#    name: Run flutter test and analyse
#    # VM type and version that runs this code
#    runs-on: ubuntu-latest
#    steps:
#      # Any prerequisite steps
#      - uses: actions/checkout@v2
#      - uses: actions/setup-java@v1
#        with:
#          java-version: "12.x"
#      # Module that allows us to run flutter commands
#      - uses: subosito/flutter-action@v1
#        with:
#          channel: "stable"
#      - run: flutter pub get
#      - run: flutter analyze
#      - run: flutter test
#
#  build_web:
#    name: Build and deploy flutter (web)
#    needs: [flutter_test]
#    # VM type and version that runs this code
#    runs-on: ubuntu-latest
#    steps:
#      # Any prerequisite steps
#      - uses: actions/checkout@v2
#      - uses: actions/setup-java@v1
#        with:
#          java-version: "12.x"
#      # Module that allows us to run flutter commands
#      - uses: subosito/flutter-action@v1
#        with:
#          channel: "stable"
#      - run: flutter pub get
#      - run: flutter clean
#      - run: flutter build web --release
#
#      # Deploy to local repo
#      - name: Push web build to gh-pages
#        uses: s0/git-publish-subdir-action@v2.5.1
#        env:
#          REPO: self
#          BRANCH: gh-pages
#          FOLDER: web
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}