# Workflow name
name: Deploy to GitHub Pages

# Events that trigger this workflow
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    # VM type and version that runs this code
    runs-on: ubuntu-latest
    steps:

      # Any prerequisite steps
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      # Module that allows us to run flutter commands
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter analyse
      - run: flutter test

      # Build application
      - name: Build flutter web
          run: flutter build web --release

      # Deploy to local repo
      - name: Push web build to gh-pages
        uses: s0/git-publish-subdir-action@v2.5.1
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: web
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}